# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: r1cc4r2o/r1cc4r2o.github.io:slim
    #build: .
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
